import { useState } from "react";
import { useWindowStore } from "../../store/windowStore";
import { assetUrl } from "../../utils/assets";

export default function ShutdownDialog({ id }: { id: string }) {
  const [action, setAction] = useState("shut-down");
  const closeWindow = useWindowStore((state) => state.closeWindow);
  const confirm = () => window.dispatchEvent(new CustomEvent("zarxp-power", { detail: { action } }));

  return <div className="xp-dialog-surface"><div className="xp-dialog-body"><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}><div style={{ width: 38, height: 38, display: "flex", alignItems: "center", justifyContent: "center", background: "linear-gradient(180deg,#F28A5E,#D43B1E)", border: "1px solid #B22B10", borderRadius: 4 }}><img src={assetUrl("assets/icons/Power.png")} alt="" style={{ width: 24, height: 24 }} /></div><div><div style={{ fontWeight: "bold", color: "#0A246A" }}>Shut Down Windows</div><div>What do you want the computer to do?</div></div></div><div className="xp-group-box"><label className="xp-form-row"><input className="xp-native-checkbox" type="radio" name="shutdown-action" checked={action === "shut-down"} onChange={() => setAction("shut-down")} />Shut down</label><label className="xp-form-row"><input className="xp-native-checkbox" type="radio" name="shutdown-action" checked={action === "restart"} onChange={() => setAction("restart")} />Restart</label><label className="xp-form-row"><input className="xp-native-checkbox" type="radio" name="shutdown-action" checked={action === "stand-by"} onChange={() => setAction("stand-by")} />Stand by</label><div className="xp-form-row" style={{ marginTop: 8 }}><label className="xp-form-label" htmlFor="shutdown-option">Option:</label><select id="shutdown-option" className="xp-select" value={action} onChange={(event) => setAction(event.target.value)}><option value="shut-down">Shut down</option><option value="restart">Restart</option><option value="stand-by">Stand by</option></select></div></div></div><div className="xp-dialog-footer center"><button className="xp-button" onClick={confirm}>OK</button><button className="xp-button" onClick={() => closeWindow(id)}>Cancel</button><button className="xp-button">Help</button></div></div>;
}
