import { create } from "zustand";

export type Lang = "en" | "es";

const KEY = "zarxp-lang";

const STRINGS = {
  en: {
    start: "start",
    internet: "Internet",
    email: "E-mail",
    tour: "Tour Windows XP",
    messenger: "Windows Messenger",
    mediaPlayer: "Windows Media Player",
    publicForum: "Public Forum",
    wordpad: "Wordpad",
    paint: "Paint",
    allPrograms: "All Programs",
    myDocuments: "My Documents",
    myPictures: "My Pictures",
    myMusic: "My Music",
    myVideos: "My Videos",
    myComputer: "My Computer",
    controlPanel: "Control Panel",
    setProgramAccess: "Set Program Access and Defaults",
    helpAndSupport: "Help And Support",
    search: "Search",
    run: "Run...",
    logOff: "Log Off",
    turnOff: "Turn Off Computer",
    myNetworkPlaces: "My Network Places",
    recycleBin: "Recycle Bin",
    internetExplorer: "Internet Explorer",
    balloonTourTitle: "Take a tour of Windows XP",
    balloonTourBody: "To learn about the fun features Windows XP has to offer, |click here|. To find this info later, click Help and About on the Start menu.",
    balloonRemoveTitle: "Safely Remove Hardware",
    balloonRemoveBody: "No removable devices are connected.",
    volume: "Volume",
    mute: "Mute",
    shutDown: "Shut down",
    restart: "Restart",
    standBy: "Stand by",
    shutDownWindows: "Shut Down Windows",
    whatToDo: "What do you want the computer to do?",
    option: "Option:",
    shuttingDown: "Windows is shutting down...",
    welcome: "welcome",
    loadingPersonal: "Loading your personal settings...",
    toBegin: "To begin, click your user name",
    afterLogon: "After you log on, you can add or change accounts.",
    controlPanelUser: "Just go to Control Panel and click User Accounts.",
    turnOffComputer: "Turn off computer",
    regionalOptions: "Regional and Language Options",

    taskManager: "Windows Task Manager",
    applications: "Applications",
    processes: "Processes",
    performance: "Performance",
    networking: "Networking",
    users: "Users",
    task: "Task",
    status: "Status",
    running: "Running",
    endTask: "End Task",
    switchTo: "Switch To",
    newTask: "New Task...",
    imageName: "Image Name",
    cpu: "CPU",
    memUsage: "Mem Usage",
    endProcess: "End Process",
    cpuUsage: "CPU Usage",
    cpuUsageHistory: "CPU Usage History",
    memUsageHistory: "PF Usage",
    totals: "Totals",
    handles: "Handles",
    threads: "Threads",
    physicalMemory: "Physical Memory (K)",
    commitCharge: "Commit Charge (K)",
    kernelMemory: "Kernel Memory (K)",

    arrangeIconsBy: "Arrange Icons By",
    byName: "Name",
    bySize: "Size",
    byType: "Type",
    byModified: "Modified",
    autoArrange: "Auto Arrange",
    alignToGrid: "Align to Grid",
    refresh: "Refresh",
    paste: "Paste",
    pasteShortcut: "Paste Shortcut",
    new: "New",
    folder: "Folder",
    textDocument: "Text Document",
    bitmapImage: "Bitmap Image",
    wordpadDocument: "WordPad Document",
    properties: "Properties",

    toolbars: "Toolbars",
    cascadeWindows: "Cascade Windows",
    tileHorizontally: "Tile Windows Horizontally",
    tileVertically: "Tile Windows Vertically",
    showDesktop: "Show the Desktop",
    lockTaskbar: "Lock the Taskbar",
    taskbarProperties: "Properties",

    playlist: "PLAYLIST",
    prev: "Previous",
    play: "Play",
    pause: "Pause",
    stop: "Stop",
    next: "Next",

    pickCategory: "Pick a category",
    classicView: "Classic View",
    switchToClassic: "Switch to Classic View",
    switchToCategory: "Switch to Category View",
    seeAlso: "See Also",
    systemInformation: "System Information",
    appearanceAndThemes: "Appearance and Themes",
    appearanceAndThemesDesc: "Change the appearance of desktop items, apply a screen saver, or choose a theme.",
    networkAndInternet: "Network and Internet Connections",
    networkAndInternetDesc: "Connect to the Internet, set up a home or small office network, or change modem settings.",
    userAccountsCat: "User Accounts",
    userAccountsDesc: "Change user account settings, passwords, and user pictures.",
    dateTimeRegional: "Date, Time, Language, and Regional Options",
    dateTimeRegionalDesc: "Change the date, time, time zone, language, and the way numbers, currencies, and dates are displayed.",
    soundsSpeechAudio: "Sounds, Speech, and Audio Devices",
    soundsSpeechAudioDesc: "Change the sound scheme for your computer, or configure the settings for your speakers and recording devices.",
    performanceMaintenance: "Performance and Maintenance",
    performanceMaintenanceDesc: "View information about your computer, manage system performance, and free up hard disk space.",
    securityCenterCat: "Security Center",
    securityCenterDesc: "Configure firewalls, automatic updates, and virus protection settings.",
    administrativeTools: "Administrative Tools",
    administrativeToolsDesc: "Configure administrative settings, services, and diagnostic consoles.",

    dateAndTime: "Date and Time",
    dateAndTimeDesc: "Set date, time, and time zone",
    displayClassic: "Display",
    displayClassicDesc: "Change desktop display and wallpaper",
    networkConnectionsClassic: "Network Connections",
    networkConnectionsClassicDesc: "Manage local networks and connections",
    securityCenterClassic: "Security Center",
    securityCenterClassicDesc: "Check computer security status",
    soundsAudioClassic: "Sounds and Audio Devices",
    soundsAudioClassicDesc: "Adjust volume and audio devices",
    systemClassic: "System",
    systemClassicDesc: "View system hardware and performance",

    searchCompanion: "Search Companion",
    whatSearchFor: "What do you want to search for?",
    picturesAndPhotos: "Pictures and photos",
    documentsSearch: "Documents (word processing, spreadsheet, etc.)",
    musicAndSound: "Music and sound",
    allFilesFolders: "All files and folders",
    computersOrPeople: "Computers or people",
    infoOnInternet: "Information on the Internet",
    partOfFileName: "All or part of the file name:",
    searchBtn: "Search",
    cancelBtn: "Cancel",
    searchResults: "Search Results",
    whatFind: "What do you want to find?",
    toStartSearch: "To start your search, follow the instructions in the left pane.",
    closeBtn: "Close",
  },
  es: {
    start: "inicio",
    internet: "Internet",
    email: "Correo",
    tour: "Tour de Windows XP",
    messenger: "Windows Messenger",
    mediaPlayer: "Reproductor de Windows Media",
    publicForum: "Foro publico",
    wordpad: "Wordpad",
    paint: "Paint",
    allPrograms: "Todos los programas",
    myDocuments: "Mis documentos",
    myPictures: "Mis imagenes",
    myMusic: "Mi musica",
    myVideos: "Mis videos",
    myComputer: "Mi PC",
    controlPanel: "Panel de control",
    setProgramAccess: "Establecer acceso a programas",
    helpAndSupport: "Ayuda y soporte tecnico",
    search: "Buscar",
    run: "Ejecutar...",
    logOff: "Cerrar sesion",
    turnOff: "Apagar el equipo",
    myNetworkPlaces: "Mis sitios de red",
    recycleBin: "Papelera de reciclaje",
    internetExplorer: "Internet Explorer",
    balloonTourTitle: "Haga un tour por Windows XP",
    balloonTourBody: "Para conocer las funciones mas divertidas de Windows XP, |haga clic aqui|. Para ver esta informacion mas tarde, haga clic en Ayuda y Acerca de en el menu Inicio.",
    balloonRemoveTitle: "Quitar hardware de forma segura",
    balloonRemoveBody: "No hay dispositivos extraibles conectados.",
    volume: "Volumen",
    mute: "Silenciar",
    shutDown: "Apagar",
    restart: "Reiniciar",
    standBy: "En espera",
    shutDownWindows: "Apagar Windows",
    whatToDo: "Que desea hacer con el equipo?",
    option: "Opcion:",
    shuttingDown: "Windows se esta cerrando...",
    welcome: "bienvenido",
    loadingPersonal: "Cargando la configuracion personal...",
    toBegin: "Para empezar, haga clic en su nombre de usuario",
    afterLogon: "Despues de iniciar sesion puede agregar o cambiar cuentas.",
    controlPanelUser: "Vaya al Panel de control y haga clic en Cuentas de usuario.",
    turnOffComputer: "Apagar el equipo",
    regionalOptions: "Opciones regionales y de idioma",

    taskManager: "Administrador de tareas de Windows",
    applications: "Aplicaciones",
    processes: "Procesos",
    performance: "Rendimiento",
    networking: "Funciones de red",
    users: "Usuarios",
    task: "Tarea",
    status: "Estado",
    running: "En ejecucion",
    endTask: "Finalizar tarea",
    switchTo: "Traer al frente",
    newTask: "Nueva tarea...",
    imageName: "Nombre de imagen",
    cpu: "CPU",
    memUsage: "Uso de memoria",
    endProcess: "Finalizar proceso",
    cpuUsage: "Uso de CPU",
    cpuUsageHistory: "Historial de uso de CPU",
    memUsageHistory: "Uso de archivo de paginacion",
    totals: "Totales",
    handles: "Identificadores",
    threads: "Subprocesos",
    physicalMemory: "Memoria fisica (K)",
    commitCharge: "Carga de transacciones (K)",
    kernelMemory: "Memoria del nucleo (K)",

    arrangeIconsBy: "Organizar iconos por",
    byName: "Nombre",
    bySize: "Tamano",
    byType: "Tipo",
    byModified: "Modificado",
    autoArrange: "Organizacion automatica",
    alignToGrid: "Alinear a la cuadricula",
    refresh: "Actualizar",
    paste: "Pegar",
    pasteShortcut: "Pegar acceso directo",
    new: "Nuevo",
    folder: "Carpeta",
    textDocument: "Documento de texto",
    bitmapImage: "Imagen de mapa de bits",
    wordpadDocument: "Documento de WordPad",
    properties: "Propiedades",

    toolbars: "Barras de herramientas",
    cascadeWindows: "Ventanas en cascada",
    tileHorizontally: "Mosaico horizontal",
    tileVertically: "Mosaico vertical",
    showDesktop: "Mostrar el escritorio",
    lockTaskbar: "Bloquear la barra de tareas",
    taskbarProperties: "Propiedades",

    playlist: "LISTA DE REPRODUCCION",
    prev: "Anterior",
    play: "Reproducir",
    pause: "Pausar",
    stop: "Detener",
    next: "Siguiente",

    pickCategory: "Elija una categoria",
    classicView: "Vista clasica",
    switchToClassic: "Cambiar a Vista clasica",
    switchToCategory: "Cambiar a Vista por categorias",
    seeAlso: "Vea tambien",
    systemInformation: "Informacion del sistema",
    appearanceAndThemes: "Apariencia y temas",
    appearanceAndThemesDesc: "Cambie la apariencia de los elementos del escritorio, aplique un protector de pantalla o elija un tema.",
    networkAndInternet: "Conexiones de red e Internet",
    networkAndInternetDesc: "Conectese a Internet, configure una red domestica o de oficina pequena, o cambie la configuracion del modem.",
    userAccountsCat: "Cuentas de usuario",
    userAccountsDesc: "Cambie la configuracion de las cuentas de usuario, las contrasenas y las imagenes de usuario.",
    dateTimeRegional: "Opciones de fecha, hora, idioma y regionales",
    dateTimeRegionalDesc: "Cambie la fecha, hora, zona horaria, idioma y el formato de numeros, monedas y fechas.",
    soundsSpeechAudio: "Sonidos, voz y dispositivos de audio",
    soundsSpeechAudioDesc: "Cambie el esquema de sonido de su equipo o configure los altavoces y los dispositivos de grabacion.",
    performanceMaintenance: "Rendimiento y mantenimiento",
    performanceMaintenanceDesc: "Vea informacion sobre el equipo, ajuste el rendimiento y libere espacio en el disco duro.",
    securityCenterCat: "Centro de seguridad",
    securityCenterDesc: "Configure firewall, actualizaciones automaticas y proteccion antivirus.",
    administrativeTools: "Herramientas administrativas",
    administrativeToolsDesc: "Configure opciones administrativas, servicios y consolas de diagnostico.",

    dateAndTime: "Fecha y hora",
    dateAndTimeDesc: "Ajuste fecha, hora y zona horaria",
    displayClassic: "Pantalla",
    displayClassicDesc: "Cambie fondo y resolucion de pantalla",
    networkConnectionsClassic: "Conexiones de red",
    networkConnectionsClassicDesc: "Administre redes y conexiones",
    securityCenterClassic: "Centro de seguridad",
    securityCenterClassicDesc: "Compruebe la seguridad del equipo",
    soundsAudioClassic: "Dispositivos de sonido y audio",
    soundsAudioClassicDesc: "Ajuste volumen y dispositivos",
    systemClassic: "Sistema",
    systemClassicDesc: "Vea hardware y rendimiento del sistema",

    searchCompanion: "Asistente de busqueda",
    whatSearchFor: "Que desea buscar?",
    picturesAndPhotos: "Imagenes y fotos",
    documentsSearch: "Documentos (procesador de textos, hoja de calculo, etc.)",
    musicAndSound: "Musica y sonido",
    allFilesFolders: "Todos los archivos y carpetas",
    computersOrPeople: "Equipos o personas",
    infoOnInternet: "Informacion en Internet",
    partOfFileName: "Todo o parte del nombre de archivo:",
    searchBtn: "Buscar",
    cancelBtn: "Cancelar",
    searchResults: "Resultados de la busqueda",
    whatFind: "Que desea buscar?",
    toStartSearch: "Para iniciar la busqueda, siga las instrucciones del panel izquierdo.",
    closeBtn: "Cerrar",
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;

interface LangStore {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: StringKey) => string;
}

function initial(): Lang {
  try {
    const v = localStorage.getItem(KEY);
    if (v === "en" || v === "es") return v;
  } catch {}
  return "en";
}

export const useLangStore = create<LangStore>((set, get) => ({
  lang: initial(),
  setLang: (lang) => {
    set({ lang });
    try { localStorage.setItem(KEY, lang); } catch {}
  },
  t: (key) => STRINGS[get().lang][key] || key,
}));
