import { create } from "zustand";

export type Lang = "en" | "es";

const KEY = "zarxp-lang";

const STRINGS = {
  en: {
    start: "start",
    internet: "Internet",
    email: "E-mail",
    tour: "Tour Windows XP",
    messenger: "Windows Messenger",
    mediaPlayer: "Windows Media Player",
    publicForum: "Public Forum",
    wordpad: "Wordpad",
    paint: "Paint",
    allPrograms: "All Programs",
    myDocuments: "My Documents",
    myPictures: "My Pictures",
    myMusic: "My Music",
    myVideos: "My Videos",
    myComputer: "My Computer",
    controlPanel: "Control Panel",
    setProgramAccess: "Set Program Access and Defaults",
    helpAndSupport: "Help And Support",
    search: "Search",
    run: "Run...",
    runCannotFind: "Windows cannot find this command.",
    logOff: "Log Off",
    turnOff: "Turn Off Computer",
    myNetworkPlaces: "My Network Places",
    recycleBin: "Recycle Bin",
    internetExplorer: "Internet Explorer",
    balloonTourTitle: "Take a tour of Windows XP",
    balloonTourBody: "To learn about the fun features Windows XP has to offer, |click here|. To find this info later, click Help and About on the Start menu.",
    balloonRemoveTitle: "Safely Remove Hardware",
    balloonRemoveBody: "No removable devices are connected.",
    volume: "Volume",
    safelyRemoveHardware: "Safely Remove Hardware",
    dateTimeProperties: "Date and Time Properties",
    mute: "Mute",
    shutDown: "Shut down",
    restart: "Restart",
    standBy: "Stand by",
    shutDownWindows: "Shut Down Windows",
    whatToDo: "What do you want the computer to do?",
    option: "Option:",
    shuttingDown: "Windows is shutting down...",
    welcome: "welcome",
    loadingPersonal: "Loading your personal settings...",
    toBegin: "To begin, click your user name",
    afterLogon: "After you log on, you can add or change accounts.",
    controlPanelUser: "Just go to Control Panel and click User Accounts.",
    turnOffComputer: "Turn off computer",
    regionalOptions: "Regional and Language Options",

    taskManager: "Windows Task Manager",
    applications: "Applications",
    processes: "Processes",
    performance: "Performance",
    networking: "Networking",
    users: "Users",
    task: "Task",
    status: "Status",
    running: "Running",
    endTask: "End Task",
    switchTo: "Switch To",
    newTask: "New Task...",
    imageName: "Image Name",
    cpu: "CPU",
    memUsage: "Mem Usage",
    endProcess: "End Process",
    cpuUsage: "CPU Usage",
    cpuUsageHistory: "CPU Usage History",
    memUsageHistory: "PF Usage",
    totals: "Totals",
    handles: "Handles",
    threads: "Threads",
    userName: "User Name",
    showAllUsers: "Show processes from all users",
    pageFileUsageHistory: "Page File Usage History",
    processesLabel: "Processes",
    total: "Total",
    available: "Available",
    systemCache: "System Cache",
    localAreaConnection: "Local Area Connection",
    networkUtilization: "Network Utilization",
    user: "User",
    id: "ID",
    clientName: "Client Name",
    active: "Active",
    console: "Console",
    processesStatus: "Processes",
    cpuUsageStatus: "CPU Usage",
    commitChargeStatus: "Commit Charge",
    physicalMemory: "Physical Memory (K)",
    commitCharge: "Commit Charge (K)",
    kernelMemory: "Kernel Memory (K)",

    arrangeIconsBy: "Arrange Icons By",
    byName: "Name",
    bySize: "Size",
    byType: "Type",
    byModified: "Modified",
    autoArrange: "Auto Arrange",
    alignToGrid: "Align to Grid",
    refresh: "Refresh",
    paste: "Paste",
    pasteShortcut: "Paste Shortcut",
    new: "New",
    folder: "Folder",
    textDocument: "Text Document",
    bitmapImage: "Bitmap Image",
    wordpadDocument: "WordPad Document",
    properties: "Properties",

    toolbars: "Toolbars",
    cascadeWindows: "Cascade Windows",
    tileHorizontally: "Tile Windows Horizontally",
    tileVertically: "Tile Windows Vertically",
    showDesktop: "Show the Desktop",
    lockTaskbar: "Lock the Taskbar",
    taskbarProperties: "Properties",

    playlist: "PLAYLIST",
    prev: "Previous",
    play: "Play",
    pause: "Pause",
    stop: "Stop",
    next: "Next",

    pickCategory: "Pick a category",
    classicView: "Classic View",
    switchToClassic: "Switch to Classic View",
    switchToCategory: "Switch to Category View",
    seeAlso: "See Also",
    systemInformation: "System Information",
    appearanceAndThemes: "Appearance and Themes",
    appearanceAndThemesDesc: "Change the appearance of desktop items, apply a screen saver, or choose a theme.",
    networkAndInternet: "Network and Internet Connections",
    networkAndInternetDesc: "Connect to the Internet, set up a home or small office network, or change modem settings.",
    userAccountsCat: "User Accounts",
    userAccountsDesc: "Change user account settings, passwords, and user pictures.",
    dateTimeRegional: "Date, Time, Language, and Regional Options",
    dateTimeRegionalDesc: "Change the date, time, time zone, language, and the way numbers, currencies, and dates are displayed.",
    soundsSpeechAudio: "Sounds, Speech, and Audio Devices",
    soundsSpeechAudioDesc: "Change the sound scheme for your computer, or configure the settings for your speakers and recording devices.",
    performanceMaintenance: "Performance and Maintenance",
    performanceMaintenanceDesc: "View information about your computer, manage system performance, and free up hard disk space.",
    securityCenterCat: "Security Center",
    securityCenterDesc: "Configure firewalls, automatic updates, and virus protection settings.",
    administrativeTools: "Administrative Tools",
    administrativeToolsDesc: "Configure administrative settings, services, and diagnostic consoles.",

    dateAndTime: "Date and Time",
    dateAndTimeDesc: "Set date, time, and time zone",
    displayClassic: "Display",
    displayClassicDesc: "Change desktop display and wallpaper",
    networkConnectionsClassic: "Network Connections",
    networkConnectionsClassicDesc: "Manage local networks and connections",
    securityCenterClassic: "Security Center",
    securityCenterClassicDesc: "Check computer security status",
    soundsAudioClassic: "Sounds and Audio Devices",
    soundsAudioClassicDesc: "Adjust volume and audio devices",
    systemClassic: "System",
    systemClassicDesc: "View system hardware and performance",

    searchCompanion: "Search Companion",
    whatSearchFor: "What do you want to search for?",
    picturesAndPhotos: "Pictures and photos",
    documentsSearch: "Documents (word processing, spreadsheet, etc.)",
    musicAndSound: "Music and sound",
    allFilesFolders: "All files and folders",
    computersOrPeople: "Computers or people",
    infoOnInternet: "Information on the Internet",
    partOfFileName: "All or part of the file name:",
    searchBtn: "Search",
    cancelBtn: "Cancel",
    searchResults: "Search Results",
    whatFind: "What do you want to find?",
    toStartSearch: "To start your search, follow the instructions in the left pane.",
    closeBtn: "Close",
    minimize: "Minimize",
    maximize: "Maximize",
    restore: "Restore",
    close: "Close",
    file: "File",
    edit: "Edit",
    view: "View",
    favorites: "Favorites",
    tools: "Tools",
    help: "Help",
    back: "Back",
    forward: "Forward",
    up: "Up",
    delete: "Delete",
    folders: "Folders",
    views: "Views",
    address: "Address",
    go: "Go",
    fileFolder: "File Folder",
    textDocumentType: "Text Document",
    microsoftWordDocument: "Microsoft Word Document",
    jpegImage: "JPEG Image",
    pngImage: "PNG Image",
    document: "Document",
    typeLabel: "Type",
    sizeLabel: "Size",
    objects: "object(s)",
    systemTasks: "System Tasks",
    viewSystemInformation: "View system information",
    addOrRemovePrograms: "Add or remove programs",
    changeASetting: "Change a setting",
    otherPlaces: "Other Places",
    details: "Details",
    systemFolder: "System Folder",
    filesStoredIn: "Files Stored in",
    folderEmpty: "This folder is empty.",
    recycleBinTasks: "Recycle Bin Tasks",
    emptyRecycleBin: "Empty Recycle Bin",
    restoreSelectedItem: "Restore selected item",
    deletedItems: "Deleted items",
    name: "Name",
    originalLocation: "Original Location",
    dateDeleted: "Date Deleted",
    recycleBinEmpty: "Recycle Bin is empty.",
    itemCount: "item(s)",
    themes: "Themes",
    desktop: "Desktop",
    screenSaver: "Screen Saver",
    appearance: "Appearance",
    settingsTab: "Settings",
    theme: "Theme",
    classic: "Classic",
    samplePreview: "Sample Preview",
    background: "Background",
    none: "None",
    wallpaperPreview: "Wallpaper Preview",
    solidColor: "Solid Color",
    screenSaverLabel: "Screen saver",
    wait: "Wait",
    minutes: "minutes",
    colorScheme: "Color scheme",
    defaultColor: "Default",
    silver: "Silver",
    oliveGreen: "Olive Green",
    fontSize: "Font size",
    normal: "Normal",
    large: "Large",
    extraLarge: "Extra Large",
    screenResolution: "Screen resolution",
    colorQuality: "Color quality",
    highestQuality: "Highest (32 bit)",
    highQuality: "High (24 bit)",
    mediumQuality: "Medium (16 bit)",
    ok: "OK",
    cancel: "Cancel",
    apply: "Apply",
    runDescription: "Type the name of a program, folder, or document, and Windows will open it for you.",
    openLabel: "Open:",
    browse: "Browse...",
    searching: "Searching...",
    noMatching: "There are no matching items in this directory.",
    searchingFiles: "Searching files...",
    newFile: "New",
    openFile: "Open",
    saveFile: "Save",
    wordWrap: "Word Wrap",
    windowsCrlf: "Windows (CRLF)",
    utf8: "UTF-8",
    untitled: "Untitled.txt",
    notEditable: "This file type cannot be edited as text.",
    fileNotFound: "File not found.",
    previewUnavailable: "Preview unavailable for this file type.",
    fileReadError: "Unable to read the selected file.",
    emptyTrashConfirm: "Are you sure you want to permanently delete these items?",
    screenSaverActive: "Windows XP Screen Saver",
  },
  es: {
    start: "inicio",
    internet: "Internet",
    email: "Correo",
    tour: "Tour de Windows XP",
    messenger: "Windows Messenger",
    mediaPlayer: "Reproductor de Windows Media",
    publicForum: "Foro publico",
    wordpad: "Wordpad",
    paint: "Paint",
    allPrograms: "Todos los programas",
    myDocuments: "Mis documentos",
    myPictures: "Mis imagenes",
    myMusic: "Mi musica",
    myVideos: "Mis videos",
    myComputer: "Mi PC",
    controlPanel: "Panel de control",
    setProgramAccess: "Establecer acceso a programas",
    helpAndSupport: "Ayuda y soporte tecnico",
    search: "Buscar",
    run: "Ejecutar...",
    runCannotFind: "Windows no puede encontrar este comando.",
    logOff: "Cerrar sesion",
    turnOff: "Apagar el equipo",
    myNetworkPlaces: "Mis sitios de red",
    recycleBin: "Papelera de reciclaje",
    internetExplorer: "Internet Explorer",
    balloonTourTitle: "Haga un tour por Windows XP",
    balloonTourBody: "Para conocer las funciones mas divertidas de Windows XP, |haga clic aqui|. Para ver esta informacion mas tarde, haga clic en Ayuda y Acerca de en el menu Inicio.",
    balloonRemoveTitle: "Quitar hardware de forma segura",
    balloonRemoveBody: "No hay dispositivos extraibles conectados.",
    volume: "Volumen",
    safelyRemoveHardware: "Quitar hardware de forma segura",
    dateTimeProperties: "Propiedades de fecha y hora",
    mute: "Silenciar",
    shutDown: "Apagar",
    restart: "Reiniciar",
    standBy: "En espera",
    shutDownWindows: "Apagar Windows",
    whatToDo: "Que desea hacer con el equipo?",
    option: "Opcion:",
    shuttingDown: "Windows se esta cerrando...",
    welcome: "bienvenido",
    loadingPersonal: "Cargando la configuracion personal...",
    toBegin: "Para empezar, haga clic en su nombre de usuario",
    afterLogon: "Despues de iniciar sesion puede agregar o cambiar cuentas.",
    controlPanelUser: "Vaya al Panel de control y haga clic en Cuentas de usuario.",
    turnOffComputer: "Apagar el equipo",
    regionalOptions: "Opciones regionales y de idioma",

    taskManager: "Administrador de tareas de Windows",
    applications: "Aplicaciones",
    processes: "Procesos",
    performance: "Rendimiento",
    networking: "Funciones de red",
    users: "Usuarios",
    task: "Tarea",
    status: "Estado",
    running: "En ejecucion",
    endTask: "Finalizar tarea",
    switchTo: "Traer al frente",
    newTask: "Nueva tarea...",
    imageName: "Nombre de imagen",
    cpu: "CPU",
    memUsage: "Uso de memoria",
    endProcess: "Finalizar proceso",
    cpuUsage: "Uso de CPU",
    cpuUsageHistory: "Historial de uso de CPU",
    memUsageHistory: "Uso de archivo de paginacion",
    totals: "Totales",
    handles: "Identificadores",
    threads: "Subprocesos",
    userName: "Nombre de usuario",
    showAllUsers: "Mostrar procesos de todos los usuarios",
    pageFileUsageHistory: "Historial de uso de archivo de paginacion",
    processesLabel: "Procesos",
    total: "Total",
    available: "Disponible",
    systemCache: "Cache del sistema",
    localAreaConnection: "Conexion de area local",
    networkUtilization: "Utilizacion de la red",
    user: "Usuario",
    id: "ID",
    clientName: "Nombre del equipo",
    active: "Activo",
    console: "Consola",
    processesStatus: "Procesos",
    cpuUsageStatus: "Uso de CPU",
    commitChargeStatus: "Carga de transacciones",
    physicalMemory: "Memoria fisica (K)",
    commitCharge: "Carga de transacciones (K)",
    kernelMemory: "Memoria del nucleo (K)",

    arrangeIconsBy: "Organizar iconos por",
    byName: "Nombre",
    bySize: "Tamano",
    byType: "Tipo",
    byModified: "Modificado",
    autoArrange: "Organizacion automatica",
    alignToGrid: "Alinear a la cuadricula",
    refresh: "Actualizar",
    paste: "Pegar",
    pasteShortcut: "Pegar acceso directo",
    new: "Nuevo",
    folder: "Carpeta",
    textDocument: "Documento de texto",
    bitmapImage: "Imagen de mapa de bits",
    wordpadDocument: "Documento de WordPad",
    properties: "Propiedades",

    toolbars: "Barras de herramientas",
    cascadeWindows: "Ventanas en cascada",
    tileHorizontally: "Mosaico horizontal",
    tileVertically: "Mosaico vertical",
    showDesktop: "Mostrar el escritorio",
    lockTaskbar: "Bloquear la barra de tareas",
    taskbarProperties: "Propiedades",

    playlist: "LISTA DE REPRODUCCION",
    prev: "Anterior",
    play: "Reproducir",
    pause: "Pausar",
    stop: "Detener",
    next: "Siguiente",

    pickCategory: "Elija una categoria",
    classicView: "Vista clasica",
    switchToClassic: "Cambiar a Vista clasica",
    switchToCategory: "Cambiar a Vista por categorias",
    seeAlso: "Vea tambien",
    systemInformation: "Informacion del sistema",
    appearanceAndThemes: "Apariencia y temas",
    appearanceAndThemesDesc: "Cambie la apariencia de los elementos del escritorio, aplique un protector de pantalla o elija un tema.",
    networkAndInternet: "Conexiones de red e Internet",
    networkAndInternetDesc: "Conectese a Internet, configure una red domestica o de oficina pequena, o cambie la configuracion del modem.",
    userAccountsCat: "Cuentas de usuario",
    userAccountsDesc: "Cambie la configuracion de las cuentas de usuario, las contrasenas y las imagenes de usuario.",
    dateTimeRegional: "Opciones de fecha, hora, idioma y regionales",
    dateTimeRegionalDesc: "Cambie la fecha, hora, zona horaria, idioma y el formato de numeros, monedas y fechas.",
    soundsSpeechAudio: "Sonidos, voz y dispositivos de audio",
    soundsSpeechAudioDesc: "Cambie el esquema de sonido de su equipo o configure los altavoces y los dispositivos de grabacion.",
    performanceMaintenance: "Rendimiento y mantenimiento",
    performanceMaintenanceDesc: "Vea informacion sobre el equipo, ajuste el rendimiento y libere espacio en el disco duro.",
    securityCenterCat: "Centro de seguridad",
    securityCenterDesc: "Configure firewall, actualizaciones automaticas y proteccion antivirus.",
    administrativeTools: "Herramientas administrativas",
    administrativeToolsDesc: "Configure opciones administrativas, servicios y consolas de diagnostico.",

    dateAndTime: "Fecha y hora",
    dateAndTimeDesc: "Ajuste fecha, hora y zona horaria",
    displayClassic: "Pantalla",
    displayClassicDesc: "Cambie fondo y resolucion de pantalla",
    networkConnectionsClassic: "Conexiones de red",
    networkConnectionsClassicDesc: "Administre redes y conexiones",
    securityCenterClassic: "Centro de seguridad",
    securityCenterClassicDesc: "Compruebe la seguridad del equipo",
    soundsAudioClassic: "Dispositivos de sonido y audio",
    soundsAudioClassicDesc: "Ajuste volumen y dispositivos",
    systemClassic: "Sistema",
    systemClassicDesc: "Vea hardware y rendimiento del sistema",

    searchCompanion: "Asistente de busqueda",
    whatSearchFor: "Que desea buscar?",
    picturesAndPhotos: "Imagenes y fotos",
    documentsSearch: "Documentos (procesador de textos, hoja de calculo, etc.)",
    musicAndSound: "Musica y sonido",
    allFilesFolders: "Todos los archivos y carpetas",
    computersOrPeople: "Equipos o personas",
    infoOnInternet: "Informacion en Internet",
    partOfFileName: "Todo o parte del nombre de archivo:",
    searchBtn: "Buscar",
    cancelBtn: "Cancelar",
    searchResults: "Resultados de la busqueda",
    whatFind: "Que desea buscar?",
    toStartSearch: "Para iniciar la busqueda, siga las instrucciones del panel izquierdo.",
    closeBtn: "Cerrar",
    minimize: "Minimizar",
    maximize: "Maximizar",
    restore: "Restaurar",
    close: "Cerrar",
    file: "Archivo",
    edit: "Editar",
    view: "Ver",
    favorites: "Favoritos",
    tools: "Herramientas",
    help: "Ayuda",
    back: "Atras",
    forward: "Adelante",
    up: "Subir",
    delete: "Eliminar",
    folders: "Carpetas",
    views: "Vistas",
    address: "Direccion",
    go: "Ir",
    fileFolder: "Carpeta de archivos",
    textDocumentType: "Documento de texto",
    microsoftWordDocument: "Documento de Microsoft Word",
    jpegImage: "Imagen JPEG",
    pngImage: "Imagen PNG",
    document: "Documento",
    typeLabel: "Tipo",
    sizeLabel: "Tamano",
    objects: "objeto(s)",
    systemTasks: "Tareas del sistema",
    viewSystemInformation: "Ver informacion del sistema",
    addOrRemovePrograms: "Agregar o quitar programas",
    changeASetting: "Cambiar una configuracion",
    otherPlaces: "Otros lugares",
    details: "Detalles",
    systemFolder: "Carpeta del sistema",
    filesStoredIn: "Archivos almacenados en",
    folderEmpty: "Esta carpeta esta vacia.",
    recycleBinTasks: "Tareas de Papelera de reciclaje",
    emptyRecycleBin: "Vaciar Papelera de reciclaje",
    restoreSelectedItem: "Restaurar elemento seleccionado",
    deletedItems: "Elementos eliminados",
    name: "Nombre",
    originalLocation: "Ubicacion original",
    dateDeleted: "Fecha de eliminacion",
    recycleBinEmpty: "La Papelera de reciclaje esta vacia.",
    itemCount: "elemento(s)",
    themes: "Temas",
    desktop: "Escritorio",
    screenSaver: "Protector de pantalla",
    appearance: "Apariencia",
    settingsTab: "Configuracion",
    theme: "Tema",
    classic: "Clasico",
    samplePreview: "Vista previa",
    background: "Fondo",
    none: "Ninguno",
    wallpaperPreview: "Vista previa del fondo",
    solidColor: "Color solido",
    screenSaverLabel: "Protector de pantalla",
    wait: "Esperar",
    minutes: "minutos",
    colorScheme: "Esquema de colores",
    defaultColor: "Predeterminado",
    silver: "Plata",
    oliveGreen: "Verde oliva",
    fontSize: "Tamano de fuente",
    normal: "Normal",
    large: "Grande",
    extraLarge: "Muy grande",
    screenResolution: "Resolucion de pantalla",
    colorQuality: "Calidad de color",
    highestQuality: "Alta (32 bits)",
    highQuality: "Alta (24 bits)",
    mediumQuality: "Media (16 bits)",
    ok: "Aceptar",
    cancel: "Cancelar",
    apply: "Aplicar",
    runDescription: "Escriba el nombre de un programa, carpeta o documento y Windows lo abrira.",
    openLabel: "Abrir:",
    browse: "Examinar...",
    searching: "Buscando...",
    noMatching: "No hay elementos coincidentes en esta carpeta.",
    searchingFiles: "Buscando archivos...",
    newFile: "Nuevo",
    openFile: "Abrir",
    saveFile: "Guardar",
    wordWrap: "Ajuste de linea",
    windowsCrlf: "Windows (CRLF)",
    utf8: "UTF-8",
    untitled: "Sin titulo.txt",
    notEditable: "Este tipo de archivo no se puede editar como texto.",
    fileNotFound: "Archivo no encontrado.",
    previewUnavailable: "No hay vista previa para este tipo de archivo.",
    fileReadError: "No se pudo leer el archivo seleccionado.",
    emptyTrashConfirm: "Esta seguro de que desea eliminar permanentemente estos elementos?",
    screenSaverActive: "Protector de pantalla de Windows XP",
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;

interface LangStore {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: StringKey) => string;
}

function initial(): Lang {
  try {
    const v = localStorage.getItem(KEY);
    if (v === "en" || v === "es") return v;
  } catch {}
  return "en";
}

export const useLangStore = create<LangStore>((set, get) => ({
  lang: initial(),
  setLang: (lang) => {
    set({ lang });
    try { localStorage.setItem(KEY, lang); } catch {}
  },
  t: (key) => STRINGS[get().lang][key] || key,
}));
